### ISSUE TITLE
Detect already installed packages in base image and filter installed packages accordingly

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#93]
The created Dockerfile can be simplified a lot by not installing packages already available in the base image, something like a "slim" build.

A potential approach:

- pull the base image
- run the image and get installed packages into R, e.g. with

```R
> pkgs <- system2(
    command = "docker",
    args = "run --rm -i rocker/verse:3.4.1 Rscript -e 'write.csv(as.data.frame(installed.packages())[,c(\"Version\")])'",
    stdout = TRUE)
> head(read.csv(text = pkgs))
           X        x
1    acepack    1.4.1
2 assertthat    0.2.0
3  backports    1.1.0
4  base64enc    0.1-3
5         BH 1.65.0-1
6      bindr      0.1

```

- filter the installation candidates, see https://stackoverflow.com/a/4090208/261210
- ~~the result of the pull and run should be stored/cached somewhere... e.g. in a well known path in a temp directory, so that the pull only happens if that value is not available (needs cache invalidation after som time, of course): `/tmp/containerit-cache/rocker_verse.20170101120000` for example, which contains the csv from `pkgs` in the above snippet~~
  - try out `R.cache`, see https://stackoverflow.com/questions/11357602/r-caching-memoise-for-environments
  - _what takes time here would be downloading the image, and that is cached by Docker_, so the calls actually evaluate fast enough without caching.
- the Dockerfile should contain a _comment_ listing the not installed packages

## Tasks

- [x] implement approach above
  - [x] extraction function
  - [x] filtering for `dockerfile(...)`
  - [x] comment in created `Dockerfile`
- [x] add to vignette (a new vignette `baseimages.Rmd`? show also how to use for tracing in `container.Rmd`)

**Comment by nuest** [comment]
This actually should not be enabled by default, since it is hindering reproducibility (less expressive Dockerfile), cf. #74

**Comment by nuest** [comment]
```
df <- dockerfile(from = "package_markdown/spacetime/",
                   maintainer = "o2r",
                   image = "rocker/geospatial:3.4.4",
                   filter_baseimage_pkgs = TRUE)
print(df)
```

gives

```
FROM rocker/geospatial:3.4.4
LABEL maintainer="o2r"
# Packages skipped because they are in the base image: abind, backports, bitops, boot, caTools, compiler, deldir, digest, evaluate, FNN, foreign, Formula, geosphere, goftest, grid, gstat, htmltools, intervals, knitr, lattice, magrittr, mapdata, maps, maptools, MASS, Matrix, MatrixModels, mgcv, mvtnorm, nlme, parallel, plyr, polyclip, quantreg, raster, RColorBrewer, Rcpp, rgdal, rmarkdown, rpart, rprojroot, sandwich, sp, spacetime, SparseM, spatstat, spatstat.data, spatstat.utils, splines, stringi, stringr, tensor, tools, xts, yaml, zoo
RUN ["install2.r", "ade4", "adehabitatLT", "adehabitatMA", "bdsmatrix", "CircStats", "cshapes", "diveMove", "DoseFinding", "KernSmooth", "lmtest", "maxLik", "miscTools", "plm", "quadprog", "SEL", "trip", "uniReg"]
WORKDIR /payload/
CMD ["R"]

```
